[package]
name = "server"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
here-now-common.workspace = true
serde.workspace = true
actionable = "0.2.0"
axum = "0.6.18"
bonsaidb = { version = "0.4.1", features = ["server", "server-instrument"] }
env_logger = "0.10.0"
futures = "0.3.28"
maud = { version = "0.25.0", features = ["axum"] }
tokio = { version = "1.29.1", features = ["full"] }
tower-http = "0.4.1"
tracing = "0.1.37"
toml_edit = { version = "0.19.12", features = ["serde"] }
anyhow.workspace = true
minijinja = "1.0.3"
