[package]
name = "server"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
here-now-common.workspace = true
serde.workspace = true
bonsaidb = { version = "0.4.1", features = ["server", "server-instrument"] }
actionable = "0.2.0"
tracing = "0.1.37"
axum = "0.6.18"
tower-http = "0.4.1"
clap = "4.3.11"
futures = "0.3.28"
tera = "1.19.0"
env_logger = "0.10.0"
maud = "0.25.0"
